version: '3'
services:
  # PostgreSQL
  postgres:
    image: 'postgres:13'
    container_name: 'starter-api-server-postgres'
    volumes:
      - './local/docker/postgresql:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
  # Adminer
  adminer:
    image: 'adminer'
    container_name: 'starter-api-server-adminer'
    links:
      - 'postgres:postgres'
    ports:
      - '3010:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DESIGN: 'pappu687'
  # MailHog
  mailhog:
    image: 'mailhog/mailhog'
    container_name: 'starter-api-server-mailhog'
    ports:
      - '587:1025'
      - '3011:8025'
